### ISSUE TITLE
Listener frequently added but not triggered

### ISSUE THREAD

**Issue by GMNGeoffrey** [zachwhaley/squashed-merge-message#11]
I'm a bit hesitant to open an issue that is basically "it doesn't work", but I'm finding that frequently the description copy isn't happening.

I added a bunch of logging to see what's going wrong, and it looks like the listener gets added but doesn't get triggered. https://github.com/GMNGeoffrey/squashed-merge-message/blob/logging/content.js

"Adding listener" shows up in the logs, but none of the other messages do. This is an intermittent issue. If I empty cache and hard reload a few times, it usually works eventually. I'll continue to try and see if I can get a reliable repro. It seems like once I've gotten it to work for a PR it works every time.

**Comment by GMNGeoffrey** [comment]
I haven't been able to repro this in incognito, so I'm guessing this is an interaction with another extension. Refined GitHub seems like the most likely contender. I already have `clear-pr-merge-commit-message` disabled, per the README. Disabling the extension was immediately followed by the description getting copied appropriately, but I also can't repro in incognito with both this and refined github enabled, so I'm not sure if that was just a coincidence.

**Comment by zachwhaley** [comment]
I have also seen this intermittent behavior, I had one user email about it, so you are not alone.  And thanks for the logging!

Unfortunately I also haven't been able to repro it and a hard refresh usually fixes it.

I'll keep more of an eye out for it now.

**Comment by zachwhaley** [comment]
I think I found how to repro this:

1. Navigate to PR webpage
2. Add a comment
3. Observe failure

**Comment by GMNGeoffrey** [comment]
I tried out using querySelectorAll to confirm it's not getting multiple results and adding the listener to the wrong element and that's not the issue (updated the branch referenced above). Maybe GitHub is deleting or re-creating the elements and the listener is getting lost? I actually can't find the listener in the side panel under the chrome dev tools (Elements > Event Listeners), but even when looking at a list for "click" that didn't include anything that looked right, it did trigger when I clicked the button.

**Comment by zachwhaley** [comment]
> I actually can't find the listener in the side panel under the chrome dev tools

I noticed that too.

I've been looking at Refined GitHub's https://github.com/sindresorhus/refined-github/blob/master/source/github-events/on-pr-merge-panel-open.ts to get an idea how they work around whatever GitHub is doing.

**Comment by GMNGeoffrey** [comment]
I'm still hitting this issue with version 2.2 @zachwhaley. I'll try to debug the cause further.

**Comment by zachwhaley** [comment]
I've seen seen happen after pressing the Update Branch button 🤔

**Comment by GMNGeoffrey** [comment]
I see it even without that, and I'm still not sure what's triggering it. Sorry I haven't had a chance to debug deeply. Something on GitHub is doing JavaScript magic that's interfering with the event listener though...

**Comment by zachwhaley** [comment]
No worries, I'm not expecting you or anyone to do more than they want 😊 

"interfering" or removing?  I still haven't tried to find my listeners in the console 😖

**Comment by GMNGeoffrey** [comment]
This hasn't been working for me at all recently and I added some debug logging. I noticed it's no longer finding the PR number element. How do you feel about making the logging on by default? I think the filtering for the correct page means it only occurs in cases of genuine issues.

For not finding the PR number, I think we can extract it from the URL instead.

**Comment by zachwhaley** [comment]
> How do you feel about making the logging on by default?

Sounds good to me 👍

**Comment by joeyparrish** [comment]
I'm currently seeing this in the logs:

```
squashed-merge-message: failed to find PR body element
```

I'll look into it and see if I can offer a PR-element PR.  :-)

**Comment by GMNGeoffrey** [comment]
Yeah I noticed that yesterday as well. It looks like GitHub has changed the html attributes around. I didn't see a good candidate attribute to grab onto when I was poking around either. I think it might require accessing it as a generic comment or something like that.

**Comment by joeyparrish** [comment]
The query `document.querySelector('.comment-form-textarea[name="pull_request[body]"]')` actually works if you first open the editor on the PR description.  It appears that the textarea is only created on-demand when it's time to edit the content.

**Comment by joeyparrish** [comment]
Here's a formula that seems to work:

1. If the PR body textarea is there, use it.
2. If not, click the edit button, then the cancel button, then try to get the body again.

**Comment by joeyparrish** [comment]
The edit button is also created on-demand, when you hover the "..." button that it lives under.

Here's another option: just query the data directly using the GitHub API and the PR number.

```js
(await (await fetch('https://api.github.com/repos/google/shaka-player/pulls/3965')).json()).body
```

**Comment by joeyparrish** [comment]
I uploaded a PR to address this.  It is pretty simple with the API.  Please take a look!
