### ISSUE TITLE
Co-authored-by Option?

### ISSUE THREAD

**Issue by ax3l** [zachwhaley/squashed-merge-message#13]
Do you think it is possible to add an option to automatically add [`Co-authored-by: ...`](https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) lines again if multiple people authored commits in a PR?

In many situations this gives credit to shared work in a PR or extensive improvements in reviews.

Only adding a co-author once would be another nice improvement over the current GH default for squashed commit messages.

**Comment by zachwhaley** [comment]
Sounds good to me.

refined-github already has this feature, but we have to disable that feature to make this extension work :P

Would you like to work on this?

**Comment by ax3l** [comment]
Sounds great, thanks :)

I opened a PR in #14.
(My JS skills are a bit rusty, please don't hesitate to suggest improvements or commit on the PR.)
