### ISSUE TITLE
Remove html comments in PR template

### ISSUE THREAD

**Issue by WeiqunZhang** [zachwhaley/squashed-merge-message#17]
Is it possible to remove html comments in the PR template?  For example, this is our PR template https://raw.githubusercontent.com/AMReX-Codes/amrex/1476ea3ef4a3dc6bae80b241d85657c0fc5d9d31/.github/pull_request_template.md  The comment part gets copied to form the commit message.

Thanks!

**Comment by zachwhaley** [comment]
Cool suggestion!

This is plausible, although you'd have to be careful not to remove HTML comments from say code blocks in the commit message.  I would say it's probable safe to remove HTML comments if they were the first thing in the PR description.

Would you like to work on this?

**Comment by WeiqunZhang** [comment]
Yes, I agree it's probably safe to remove HTML comments at the beginning of the PR description. @ax3l What do you think?

**Comment by WeiqunZhang** [comment]
I know very little about javascript.  But @ax3l from our AMReX team can probably work on it.

**Comment by zachwhaley** [comment]
@ax3l is free to work on this if they would like to, however I just wanted to make sure you were given the opportunity if you wanted it :)

Otherwise, I will work on it.

**Comment by ax3l** [comment]
I think it's a great suggestion. Please feel free to work on it @zachwhaley, I'll be out of office for a bit soon and have some more things to finish. Thank you for asking!
