### ISSUE TITLE
Sunsetting Squashed Merge Message

### ISSUE THREAD

**Issue by zachwhaley** [zachwhaley/squashed-merge-message#28]
~refined-github is considering a new feature that would basically make squashed-merge-message obsolete; see https://github.com/refined-github/refined-github/issues/5155~

~squashed-merge-message was originally created because refined-github had removed the same functionality that squashed-merge-message currently has, so if they are planning to reinstate that functionality then squashed-merge-message may no longer be necessary~

## ‼️ Update ‼️ 

**GitHub has native support for controlling the default merge message** 🎉

See the GitHub [announcement](https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/) for details.

As such, I recommend all GitHub patrons use GitHub's _default merge message_ feature instead of this web extension to both take advantage of native feature support and avoid any compatibility issues between this web extension and GitHub's implementation.

Support for Squashed Merge Message will continue until GitHub's _default merge message_ feature is added to GitHub Enterprise.
At that time, support for Squashed Merge Message will begin to sunset and eventually stop.

Thank you all for your support and contributions! 💙

**Comment by joeyparrish** [comment]
In the meantime, I very much appreciate this extension and will recommend it for all my org's projects.  Thanks!

**Comment by srijan** [comment]
I see that this feature is now added natively by Github.

https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/

**Comment by zachwhaley** [comment]
@srijan That is great news!!

I'll update the README with a link to this new feature and recommend people use that instead of my extension.

For the moment, I will continue to support this extension as I know many people are using in their organization's GitHub Enterprise instance which may not get this feature for some time.  But eventually I will probably sunset this extension 🌅
