### ISSUE TITLE
Commit message emptied

### ISSUE THREAD

**Issue by rethab** [zachwhaley/squashed-merge-message#30]
hi, I fear https://github.com/zachwhaley/squashed-merge-message/pull/29/files breaks this for me.

When I click on "Confirm Squash and Merge", the title field is set to e.g. ` (#7)` (for PR nr 7).

Here's what I found:
- This extension tries to load the title from the API, but the API responds with "too many requests"
- The function `getPrMetadataFromApi` returns `{title: '', body: ''}` in this case. 
- Later on, there are some checks like `if (!prMetadata)`. This condition is false, because `prMetadata` is an object as described in the previous step
- The effect is that the line `const commitTitle = '${prMetadata.title} (#${prNumber})';` leads to what I showed above

Environment:
- Extension Version: 4.11
- Browser: Sidekick
- GitHub: Enterprise Cloud (not the same as Enterprise Server)

Other Notes:
- There's a comment in the code `// For public repos, prefer the API.`, but this is not true. Both enterprise cloud (my case) and private repos are not public, yet the URL is `github.com`.
- I find it a bit weird that the API responds with "too many requests" in my case, because there's no way you can call this for my repository without passing authentication
- I also use Refined GitHub

**Comment by zachwhaley** [comment]
@rethab Thanks for reporting this.  I can take a look right away 🙂
