### ISSUE TITLE
squashed-merge-message doesn't seem to be working

### ISSUE THREAD

**Issue by dimberman** [zachwhaley/squashed-merge-message#33]
Hello!

Thank you for making this extension as this is a feature I would really like to get working on my github flow. I'm running into an issue where on both Edge and Chrome nothing seems to be happening even though I installed the plugin. I've tried disabling refined github entirely and that doesn't seem to work either. I've checked the console logs and am not seeing any logs as well. Any guidance would be highly appreciated. Thank you!

**Comment by dimberman** [comment]
Closing as it appears that turning refined github off entirely and then turning it back on while keeping squashed-merge-message on appears to have fixed the issue.

**Comment by zachwhaley** [comment]
@dimberman If you haven't already, please read https://github.com/zachwhaley/squashed-merge-message#refined-github-compatibility

Apart from that, there are still some oddities with this extension not loading under certain circumstances, github's page loading is a bit of a [conundrum](https://github.com/zachwhaley/squashed-merge-message/blob/main/content.js#L184).  If you happen to find a reproducible situation where the extension will not load, then please open a bug with those steps.

Thanks!
