### ISSUE TITLE
Support for merge commits

### ISSUE THREAD

**Issue by GMNGeoffrey** [zachwhaley/squashed-merge-message#7]
If I understand correctly, this is only intended to work for "squash and merge". I would love to also use it for merge commits, where GitHub's default message is also total garbage. Thoughts on adding support for this, either as an option or as the default behavior?

**Comment by zachwhaley** [comment]
Sounds good to me!

Would you like to add support for this?

**Comment by GMNGeoffrey** [comment]
Sure I can take a stab at it. I haven't done a lot of chrome extension development, so I'll probably be a bit slow to figure out the local testing part, but happy to take a stab at it. The JS looks simple :-) Do you think it needs to be an option or can just be always-on?

**Comment by GMNGeoffrey** [comment]
I can't assign myself though (if you care about the bookkeeping)

**Comment by zachwhaley** [comment]
> Do you think it needs to be an option or can just be always-on?

Let's start with always on.

**Comment by zachwhaley** [comment]
Fixed by #8

**Comment by GMNGeoffrey** [comment]
Thanks for accepting the feature :-) Please LMK when a new version is released so I can update from the webstore and point my teammates at this.

**Comment by zachwhaley** [comment]
v2.0 is out with your changes 🎉
